version: "3"
services:
  appdb1:
    container_name: appdb1
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=user2003
      - MYSQL_DATABASE=database2
  apl:
    container_name: apl
    restart: always
    build: .
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://awseb-e-5khr8nbu26-stack-awsebrdsdatabase-hvyq0iqjkpjl.c7zzcxo8qfot.eu-central-1.rds.amazonaws.com:3306/ebdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=user2003
    depends_on:
      - appdb1


